type: object
properties:
  server:
    type: object
    properties:
      openWeatherMapApiKey:
        type: string
  keycloakConfig:
    type: object
    properties:
      adminClientPasswordFile:
        type: string
