type: object
properties:
  server:
    type: object
    properties:
      openWeatherMapApiKeyFile:
        type: string
        default: '../../cert/owmapikey.txt'
  keycloakConfig:
    type: object
    properties:
      adminClientPasswordFile:
        type: string
