type: object
properties:
  server:
    type: object
    properties:
      openWeatherMapApiKeyFile:
        type: string
        default: '../../cert/owmapikey.txt'
  pathoware:
    type: object
    properties:
      northboundApi:
        type: string
      dataConnectorApi:
        type: string
  keycloakConfig:
    type: object
    properties:
      adminClientUser:
        type: string
        default: admin
      adminClientPasswordFile:
        type: string
