type: object
required:
  - id
  - type
  - name
  - status
  - owner
model:searchProperties:
  - name
db:referencedByModels:
  - model: Annotation
    property: refId
    handling: deleteObject
db:options:
  timestamps: true
properties:
  id:
    $ref: './../$defs.yaml#/NGSIentityFormat'
    description: 'Unique identifier of the entity'
    default: Incident:00000
    ui:hide:
      table: true
      form: true
  type:
    type: string
    enum:
      - Incident
    default: Incident
    ui:hide:
      form: true
      table: true
  name:
    type: string
    description: 'The name of this item.'
    ui:formItemType: text
    ui:formItemGridClass: 'col-md-6'
  status:
    type: string
    description: 'The status of this item.'
    enum:
      - open
      - successful
      - unsuccessful
      - onHold
      - cancelled
    ui:formItemType: select
    ui:i18n: true
    ui:i18nPathPrefix: enum.action.status
  description:
    type: string
    description: 'A description of this item'
    ui:formItemType: textarea
  owner:
    $ref: './../$defs.yaml#/owner'
  assignedTo:
    type: string
    ui:formItemType: select
    db:ref: User
  refId:
    type: string
    ui:formItemType: select
    db:ref: Incident
  location:
    $ref: './../$defs.yaml#/Location'
  validFrom:
    type: string
    description: 'The start of the validity period for this forecast as a ISO8601 format'
    format: date-time
    ui:formItemType: date-time
    ui:formItemGridClass: 'col-md-6'
  validTo:
    type: string
    description: 'The end of the validity period for this forecast as a ISO8601 format'
    format: date-time
    ui:formItemType: date-time
    ui:formItemGridClass: 'col-md-6'
  createdAt:
    type: string
    format: "date-time"
    db:skipInSchemaDefinition: true
  updatedAt:
    type: string
    format: "date-time"
    db:skipInSchemaDefinition: true
